def exception(message):
    print(message)
    # TODO: display the exception in UI